services:

  postgres:
    image: postgres:16
    container_name: email-campaign-postgres
    environment:
      POSTGRES_DB: email_campaign_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password@123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: email-campaign-api
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/email_campaign_dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Password@123

volumes:
  postgres_data: