spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/email_campaign_prod
    username: postgres
    password: Souvikp683@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true